name: firebase_basics
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.3.2
  firebase_analytics: ^10.1.1
  number_selector: ^1.0.5
  firebase_messaging: ^14.2.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
