// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoW15TvGBV8hfGppOcdb63--IxGyBsDDw',
    appId: '1:93690516375:web:9eb84eed69401489762ad2',
    messagingSenderId: '93690516375',
    projectId: 'fir-basics-d9147',
    authDomain: 'fir-basics-d9147.firebaseapp.com',
    storageBucket: 'fir-basics-d9147.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ToPwtVRmveiOJQ0ziLnWU9C1IWQ6ZDI',
    appId: '1:93690516375:android:99926fca20784d10762ad2',
    messagingSenderId: '93690516375',
    projectId: 'fir-basics-d9147',
    storageBucket: 'fir-basics-d9147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFwKPQri3ydDuSil67f3j2LjfARTe_OtE',
    appId: '1:93690516375:ios:7de84c9d8f2d4a20762ad2',
    messagingSenderId: '93690516375',
    projectId: 'fir-basics-d9147',
    storageBucket: 'fir-basics-d9147.appspot.com',
    iosClientId: '93690516375-plffdiv4c729sc93o722c85ndan6tuj6.apps.googleusercontent.com',
    iosBundleId: 'com.movaid.firebasebasics',
  );
}
